In [2]:
import pandas as pd
pd.__version__

'2.3.3'

In [3]:
numbers = [1, 2, 3, 4, 5]
list_sr = pd.Series(numbers)
print(list_sr)
type(list_sr)

0    1
1    2
2    3
3    4
4    5
dtype: int64

pandas.core.series.Series

In [4]:
print(list_sr.dtype, list_sr.shape, list_sr.size, list_sr.name)
print(list_sr.index)
print(list_sr.values)

int64 (5,) 5 None
RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]

In [5]:
dict_data = {"a" : 1, "b": 2, "c" : 3, "d" : 4, "e" : 5}
dict_sr = pd.Series(dict_data)
print(dict_sr)
print(dict_sr.dtype, dict_sr.shape, dict_sr.size, dict_sr.name)

a    1
b    2
c    3
d    4
e    5
dtype: int64
int64 (5,) 5 None

In [6]:
list_sr.name = 'mySeries'
list_sr

0    1
1    2
2    3
3    4
4    5
Name: mySeries, dtype: int64

In [7]:
list_sr.name

'mySeries'

In [8]:
import numpy as np
sr1 = pd.Series(numbers, dtype=np.float32)
sr1

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float32

In [9]:
chars = 'a b c d e'.split()
sr3 = pd.Series(numbers, index = chars, name='MySeries')
sr3

a    1
b    2
c    3
d    4
e    5
Name: MySeries, dtype: int64

In [10]:
sr3.index, sr3.values

(Index(['a', 'b', 'c', 'd', 'e'], dtype='object'), array([1, 2, 3, 4, 5]))

In [11]:
list_sr.index

RangeIndex(start=0, stop=5, step=1)

In [12]:
numbers = [1, 2, 3, 4, 5]
pd1 = pd.DataFrame(numbers)
pd1

   0
0  1
1  2
2  3
3  4
4  5

In [14]:
pd2 = pd.DataFrame(numbers, columns=['number'])
pd2

   number
0       1
1       2
2       3
3       4
4       5

In [26]:
score = [['정약용', 70, 80, 100],['이순신', 100, 80, 70],['이율곡', 90, 95, 90]]
score_df = pd.DataFrame(score)
score_df

     0    1   2    3
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [27]:
score_df.columns = ['이름', '국어', '영어', '수학']
score_df

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [28]:
score_df2 = pd.DataFrame(score, columns = ['이름', '국어', '영어', '수학'])
score_df2

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [29]:
score_df.shape, score_df.index, score_df.columns

((3, 4),
 RangeIndex(start=0, stop=3, step=1),
 Index(['이름', '국어', '영어', '수학'], dtype='object'))

In [30]:
score_df.dtypes

이름    object
국어     int64
영어     int64
수학     int64
dtype: object

In [31]:
print(score_df.values)

[['정약용' 70 80 100]
 ['이순신' 100 80 70]
 ['이율곡' 90 95 90]]

In [34]:
score_dict = {'이름' : ['정약용', '이순신', '이율곡', '홍길동'],'국어' : [70, 100, 90, 85],'영어' : [80, 80, 95, 100],'수학' : [100, 70, 90, 90]}
score_df = pd.DataFrame(score_dict)
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [35]:
score_df['사회'] = [85, 88, 92, 96]
score_df

    이름   국어   영어   수학  사회
0  정약용   70   80  100  85
1  이순신  100   80   70  88
2  이율곡   90   95   90  92
3  홍길동   85  100   90  96

In [36]:
score_df['총점'] = score_df.국어 + score_df.영어 + score_df.수학 + score_df.사회 # 있는 컬럼은 [' ']를 빼고 .컬럼명이라고 써도된다
score_df['평균'] = score_df.총점 / 4
score_df

    이름   국어   영어   수학  사회   총점     평균
0  정약용   70   80  100  85  335  83.75
1  이순신  100   80   70  88  338  84.50
2  이율곡   90   95   90  92  367  91.75
3  홍길동   85  100   90  96  371  92.75

In [37]:
x = [0, 1, 2, 3, 4, 5]
y = [0, 2, 4, 6, 8, 10]
df = pd.DataFrame()
df['x'] = x
df['y'] = y
df['x * y'] = df.x + df['y']
df

   x   y  x * y
0  0   0      0
1  1   2      3
2  2   4      6
3  3   6      9
4  4   8     12
5  5  10     15

In [38]:
score_df.drop(['이름'], axis)

NameError: name 'axis' is not defined

In [41]:
new_df = score_df.drop([0,2], axis=0)
new_df

    이름   국어   영어  수학  사회   총점     평균
1  이순신  100   80  70  88  338  84.50
3  홍길동   85  100  90  96  371  92.75

In [42]:
new_df.reset_index(drop=True, inplace=True)
new_df

    이름   국어   영어  수학  사회   총점     평균
0  이순신  100   80  70  88  338  84.50
1  홍길동   85  100  90  96  371  92.75

In [43]:
#### 3-5 데이터의 접근

In [46]:
score_df

    이름   국어   영어   수학  사회   총점     평균
0  정약용   70   80  100  85  335  83.75
1  이순신  100   80   70  88  338  84.50
2  이율곡   90   95   90  92  367  91.75
3  홍길동   85  100   90  96  371  92.75

In [45]:
score_df['이름']

0    정약용
1    이순신
2    이율곡
3    홍길동
Name: 이름, dtype: object

In [48]:
score_df[['이름', '총점']]

    이름   총점
0  정약용  335
1  이순신  338
2  이율곡  367
3  홍길동  371

In [49]:
score_df[1] #KeyError

KeyError: 1

In [50]:
score_df[1:2]

    이름   국어  영어  수학  사회   총점    평균
1  이순신  100  80  70  88  338  84.5

In [52]:
score_df[1:][['이름','총점']]

    이름   총점
1  이순신  338
2  이율곡  367
3  홍길동  371

In [53]:
#### 3-5-1 직접 접근 방식

In [54]:
#### 3-5-2. Boolean Indexing

In [55]:
score_df[score_df.수학>80]

    이름  국어   영어   수학  사회   총점     평균
0  정약용  70   80  100  85  335  83.75
2  이율곡  90   95   90  92  367  91.75
3  홍길동  85  100   90  96  371  92.75

In [58]:
score_df[(score_df.국어>80) & (score_df.영어>90)]

    이름  국어   영어  수학  사회   총점     평균
2  이율곡  90   95  90  92  367  91.75
3  홍길동  85  100  90  96  371  92.75

In [61]:
score_df[score_df['이름'].isin(['정약용', '이순신'])]

    이름   국어  영어   수학  사회   총점     평균
0  정약용   70  80  100  85  335  83.75
1  이순신  100  80   70  88  338  84.50

In [60]:
#### 3-5-3. 인덱서를 이용한 접근 (loc, iloc)

In [62]:
score_df

    이름   국어   영어   수학  사회   총점     평균
0  정약용   70   80  100  85  335  83.75
1  이순신  100   80   70  88  338  84.50
2  이율곡   90   95   90  92  367  91.75
3  홍길동   85  100   90  96  371  92.75

In [64]:
score_df.loc[0:2,'국어':'수학']

    국어  영어   수학
0   70  80  100
1  100  80   70
2   90  95   90

In [68]:
score_df.iloc[0:2, 1:3]

    국어  영어
0   70  80
1  100  80

In [70]:
filename = './data/sample_data.csv'
sample_df = pd.read_csv(filename)
sample_df

FileNotFoundError: [Errno 2] No such file or directory: './data/sample_data.csv'

In [71]:
sample_df.tail(3)

NameError: name 'sample_df' is not defined

In [ ]:
len(sample_df), sample_df.shape

In [ ]:
sample_df.describe()

In [ ]:
sample_df['City'].value_counts()